import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f5f9ff" },
  header: {
    backgroundColor: "#1565c0",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "android" ? 12 : 8,
    paddingBottom: 12
  },
  headerTitle: { color: "#fff", fontSize: 18, fontWeight: "700" },
  headerSubtitle: { color: "#d8eaff", marginTop: 2, fontSize: 13 },
  networkChip: {
    marginTop: 8,
    alignSelf: "flex-start",
    backgroundColor: "#0d47a1",
    color: "#fff",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    overflow: "hidden",
    fontSize: 12
  },
  body: { flex: 1 },
  scrollContent: { padding: 14, paddingBottom: 90 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#d6e4f5",
    padding: 12
  },
  cardTitle: { color: "#0f2a45", fontWeight: "700", fontSize: 16, marginBottom: 10 },
  statsGrid: { gap: 8 },
  statCard: {
    backgroundColor: "#eaf2ff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d6e4f5",
    padding: 10
  },
  statLabel: { color: "#3e5f82", fontSize: 13 },
  statValue: { marginTop: 4, color: "#0d47a1", fontSize: 20, fontWeight: "700" },
  label: { marginTop: 8, marginBottom: 4, color: "#1c3551", fontWeight: "600" },
  input: {
    borderWidth: 1,
    borderColor: "#c6d8ed",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
    color: "#102a43"
  },
  readOnly: { backgroundColor: "#f0f5fc" },
  textArea: { minHeight: 90, textAlignVertical: "top" },
  picker: { borderWidth: 1, borderColor: "#c6d8ed", borderRadius: 10, backgroundColor: "#fff" },
  selectionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  selectableCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#d6e4f5",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 60
  },
  selectableCardActive: { borderColor: "#1565c0", backgroundColor: "#e8f0fd" },
  selectableCardText: { fontSize: 13, color: "#4a678a", textAlign: "center", fontWeight: "600" },
  selectableCardTextActive: { color: "#0d47a1", fontWeight: "700" },
  buttonRow: { marginTop: 12, flexDirection: "row", gap: 8 },
  actionButton: {
    minHeight: 46,
    borderRadius: 10,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignItems: "center"
  },
  actionFlex: { flex: 1 },
  actionPrimary: { backgroundColor: "#1565c0" },
  actionSecondary: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#9ab7db" },
  actionSmall: { minHeight: 32, paddingVertical: 4, paddingHorizontal: 16, borderRadius: 16 },
  actionText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  actionTextSmall: { fontSize: 13 },
  actionSecondaryText: { color: "#15426f" },
  preview: { width: "100%", height: 180, borderRadius: 12, marginTop: 10 },
  gpsText: { marginTop: 10, color: "#204162", fontSize: 13 },
  errorText: { marginTop: 10, color: "#b00020", fontWeight: "600" },
  successText: { marginTop: 10, color: "#12713d", fontWeight: "600" },
  recordsContainer: { flex: 1, padding: 14 },
  recordsHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  listContent: { paddingBottom: 90 },
  recordCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d6e4f5",
    padding: 10,
    marginBottom: 8
  },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  recordTitle: { color: "#0f2a45", fontWeight: "700" },
  statusPill: {
    fontSize: 11,
    fontWeight: "700",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    overflow: "hidden"
  },
  okPill: { backgroundColor: "#dff5e6", color: "#0f7a3f" },
  noPill: { backgroundColor: "#ffe4e8", color: "#b00020" },
  recordText: { marginTop: 4, color: "#2f4f70", fontSize: 13 },
  thumb: { marginTop: 8, width: 70, height: 70, borderRadius: 8 },
  emptyText: { textAlign: "center", color: "#4a678a", marginTop: 24 },
  toggleRow: { marginTop: 10, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  toggleLabel: { color: "#1c3551", fontWeight: "600" },
  toggleBtn: { minWidth: 60, alignItems: "center", borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6 },
  toggleOn: { backgroundColor: "#1565c0" },
  toggleOff: { backgroundColor: "#8faed4" },
  toggleText: { color: "#fff", fontWeight: "700" },
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
    height: 70,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4
  },
  tabButton: { flex: 1, alignItems: "center", justifyContent: "center" },
  tabPill: {
    paddingHorizontal: 20,
    paddingVertical: 4,
    borderRadius: 16,
    marginBottom: 4,
    alignItems: "center",
    justifyContent: "center"
  },
  tabPillActive: { backgroundColor: "#d3e3fd" },
  tabText: { color: "#444746", fontSize: 12, fontWeight: "500" },
  tabTextActive: { color: "#001d35", fontWeight: "700" },
  toastContainer: {
    position: "absolute",
    bottom: 100,
    left: 20,
    right: 20,
    alignItems: "center",
    zIndex: 2000
  },
  toastContent: {
    flexDirection: "row",
    backgroundColor: "#1e1e1e",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 25,
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4
  },
  toastIcon: { color: "#4caf50", fontSize: 18, fontWeight: "bold", marginRight: 10 },
  toastText: { color: "#ffffff", fontSize: 14, fontWeight: "600" },
  gridRow: { flexDirection: "row", gap: 10, marginTop: 10 },
  infoCard: { flex: 1, padding: 15, borderRadius: 16, alignItems: "center", justifyContent: "center" },
  infoCardBlue: { backgroundColor: "#e3f2fd", borderWidth: 1, borderColor: "#bbdefb" },
  infoCardGreen: { backgroundColor: "#e8f5e9", borderWidth: 1, borderColor: "#c8e6c9" },
  infoCardAmber: { backgroundColor: "#fff8e1", borderWidth: 1, borderColor: "#ffecb3" },
  infoCardPurple: { backgroundColor: "#f3e5f5", borderWidth: 1, borderColor: "#e1bee7" },
  infoLabel: { fontSize: 12, color: "#546e7a", fontWeight: "600", marginBottom: 4 },
  infoValue: { fontSize: 22, fontWeight: "800", color: "#263238" },
  banner: { padding: 16, borderRadius: 16, marginBottom: 15, alignItems: "center" },
  bannerSuccess: { backgroundColor: "#4caf50" },
  bannerWarning: { backgroundColor: "#ff9800" },
  bannerText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  progressContainer: { height: 10, backgroundColor: "#f0f0f0", borderRadius: 5, overflow: "hidden", marginTop: 8 },
  progressBar: { height: "100%", backgroundColor: "#2196f3" },
  sectionHeader: { fontSize: 14, fontWeight: "700", color: "#1565c0", marginTop: 20, marginBottom: 10, textTransform: "uppercase", letterSpacing: 1 }
});
